import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The itemmap class serves as a utility container for mapping and managing certain properties and types.
 * It provides functionalities encapsulating PROP_MAP and TYPE_MAP which are crucial parts of this class.
 * This class is designed to be non-instantiable from outside as it has a private constructor.
 * <p>
 * Fields:
 * - PROP_MAP: Represents a mapping or storage structure for certain properties.
 * - TYPE_MAP: Represents a mapping or storage structure for certain types.
 * <p>
 * Methods:
 * - itemmap(): A private constructor to restrict the instantiation of this class. This ensures that the class
 * can only be accessed through static members or methods (if any), to maintain consistency and control over
 * its usage.
 */
public final class itemmap {

    public static final Map<String, String> PROP_MAP;
    public static final Map<String, String> TYPE_MAP;
    public static final ArrayList<String> TYPES;

    static {
        LinkedHashMap<String, String> p = new LinkedHashMap<>();
        p.put("*enr", "*enr");
        p.put("*vit", "*vit");
        p.put("Deep-Wounds", "Deep-Wounds");
        p.put("abs-cold", "abs-cold");
        p.put("abs-cold%", "abs-cold%");
        p.put("abs-fire", "abs-fire");
        p.put("abs-fire%", "abs-fire%");
        p.put("abs-ltng", "abs-ltng");
        p.put("abs-ltng%", "abs-ltng%");
        p.put("ac", "ac");
        p.put("ac%", "ac%");
        p.put("ac-hth", "ac-hth");
        p.put("ac-miss", "ac-miss");
        p.put("ac/lvl", "ac/lvl");
        p.put("addxp", "addxp");
        p.put("all-stats", "all-stats");
        p.put("allskills", "allskills");
        p.put("ama", "ama");
        p.put("ass", "ass");
        p.put("att", "att");
        p.put("att%", "att%");
        p.put("att-dem/lvl", "att-dem/lvl");
        p.put("att-demon", "att-demon");
        p.put("att-skill", "att-skill");
        p.put("att-und/lvl", "att-und/lvl");
        p.put("att-undead", "att-undead");
        p.put("att/lvl", "att/lvl");
        p.put("aura", "aura");
        p.put("balance2", "balance2");
        p.put("bar", "bar");
        p.put("block", "block");
        p.put("block-skill", "block-skill");
        p.put("block2", "block2");
        p.put("blood-warp-life-reduction", "blood-warp-life-reduction");
        p.put("bloody", "bloody");
        p.put("cast-skill", "cast-skill");
        p.put("cast1", "cast1");
        p.put("cast2", "cast2");
        p.put("cast3", "cast3");
        p.put("charged", "charged");
        p.put("cheap", "cheap");
        p.put("cold-len", "cold-len");
        p.put("cold-max", "cold-max");
        p.put("cold-min", "cold-min");
        p.put("coldskill", "coldskill");
        p.put("crush", "crush");
        p.put("curse-effectiveness", "curse-effectiveness");
        p.put("curse-res", "curse-res");
        p.put("dclone-clout", "dclone-clout");
        p.put("deadly", "deadly");
        p.put("deadly/lvl", "deadly/lvl");
        p.put("death-skill", "death-skill");
        p.put("deep-wounds", "deep-wounds");
        p.put("demon-heal", "demon-heal");
        p.put("dev-clout", "dev-clout");
        p.put("dex", "dex");
        p.put("dex/lvl", "dex/lvl");
        p.put("dmg", "dmg");
        p.put("dmg%", "dmg%");
        p.put("dmg%/eth", "dmg%/eth");
        p.put("dmg%/lvl", "dmg%/lvl");
        p.put("dmg-ac", "dmg-ac");
        p.put("dmg-cold", "dmg-cold");
        p.put("dmg-dem/lvl", "dmg-dem/lvl");
        p.put("dmg-demon", "dmg-demon");
        p.put("dmg-elem", "dmg-elem");
        p.put("dmg-fire", "dmg-fire");
        p.put("dmg-ltng", "dmg-ltng");
        p.put("dmg-mag", "dmg-mag");
        p.put("dmg-max", "dmg-max");
        p.put("dmg-min", "dmg-min");
        p.put("dmg-norm", "dmg-norm");
        p.put("dmg-pois", "dmg-pois");
        p.put("dmg-to-mana", "dmg-to-mana");
        p.put("dmg-und/lvl", "dmg-und/lvl");
        p.put("dmg-undead", "dmg-undead");
        p.put("dmg/lvl", "dmg/lvl");
        p.put("dragonflight-reduction", "dragonflight-reduction");
        p.put("dru", "dru");
        p.put("dur", "dur");
        p.put("eaglehorn-raven", "eaglehorn-raven");
        p.put("ease", "ease");
        p.put("enr", "enr");
        p.put("equipped-skill", "equipped-skill");
        p.put("es-efficiency", "es-efficiency");
        p.put("ethereal", "ethereal");
        p.put("explosivearrow", "explosivearrow");
        p.put("extra-cold", "extra-cold");
        p.put("extra-fire", "extra-fire");
        p.put("extra-grizzly", "extra-grizzly");
        p.put("extra-ltng", "extra-ltng");
        p.put("extra-pois", "extra-pois");
        p.put("extra-revives", "extra-revives");
        p.put("extra-shadow", "extra-shadow");
        p.put("extra-skele-war", "extra-skele-war");
        p.put("extra-spirits", "extra-spirits");
        p.put("extra-spiritwolf", "extra-spiritwolf");
        p.put("fire-max", "fire-max");
        p.put("fire-min", "fire-min");
        p.put("fireskill", "fireskill");
        p.put("freeze", "freeze");
        p.put("gethit-skill", "gethit-skill");
        p.put("gold%", "gold%");
        p.put("gold%/lvl", "gold%/lvl");
        p.put("grims-extra-skele-mage", "grims-extra-skele-mage");
        p.put("gust-reduction", "gust-reduction");
        p.put("half-freeze", "half-freeze");
        p.put("heal-hit", "heal-hit");
        p.put("heal-kill", "heal-kill");
        p.put("hit-skill", "hit-skill");
        p.put("howl", "howl");
        p.put("hp", "hp");
        p.put("hp%", "hp%");
        p.put("hp/lvl", "hp/lvl");
        p.put("ignore-ac", "ignore-ac");
        p.put("inc-splash-radius", "inc-splash-radius");
        p.put("indestruct", "indestruct");
        p.put("joust-reduction", "joust-reduction");
        p.put("joust-reduction-zeraes", "joust-reduction-zeraes");
        p.put("kick", "kick");
        p.put("kill-skill", "kill-skill");
        p.put("knock", "knock");
        p.put("leapspeed", "leapspeed");
        p.put("levelup-skill", "levelup-skill");
        p.put("lifesteal", "lifesteal");
        p.put("lifesteal-cap", "lifesteal-cap");
        p.put("light", "light");
        p.put("light-thorns", "light-thorns");
        p.put("ltng-max", "ltng-max");
        p.put("ltng-min", "ltng-min");
        p.put("ltngskill", "ltngskill");
        p.put("mag%", "mag%");
        p.put("mag%/lvl", "mag%/lvl");
        p.put("magicarrow", "magicarrow");
        p.put("magskill", "magskill");
        p.put("mana", "mana");
        p.put("mana%", "mana%");
        p.put("mana-kill", "mana-kill");
        p.put("mana/lvl", "mana/lvl");
        p.put("manasteal", "manasteal");
        p.put("map-glob-arealevel", "map-glob-arealevel");
        p.put("map-glob-boss-dropcorruptedunique", "map-glob-boss-dropcorruptedunique");
        p.put("map-glob-boss-dropfacet", "map-glob-boss-dropfacet");
        p.put("map-glob-boss-droppuzzlebox", "map-glob-boss-droppuzzlebox");
        p.put("map-glob-boss-dropskillers", "map-glob-boss-dropskillers");
        p.put("map-glob-boss-dropubermats", "map-glob-boss-dropubermats");
        p.put("map-glob-density", "map-glob-density");
        p.put("map-glob-dropcorrupted", "map-glob-dropcorrupted");
        p.put("map-glob-monsterrarity", "map-glob-monsterrarity");
        p.put("map-mon-att-pierce", "map-mon-att-pierce");
        p.put("map-mon-crush", "map-mon-crush");
        p.put("map-mon-curseresist-hp%", "map-mon-curseresist-hp%");
        p.put("map-mon-deadlystrike", "map-mon-deadlystrike");
        p.put("map-mon-dropcharms", "map-mon-dropcharms");
        p.put("map-mon-dropjewels", "map-mon-dropjewels");
        p.put("map-mon-hp%", "map-mon-hp%");
        p.put("map-mon-phys-as-extra-cold", "map-mon-phys-as-extra-cold");
        p.put("map-mon-phys-as-extra-fire", "map-mon-phys-as-extra-fire");
        p.put("map-mon-phys-as-extra-ltng", "map-mon-phys-as-extra-ltng");
        p.put("map-mon-phys-as-extra-mag", "map-mon-phys-as-extra-mag");
        p.put("map-mon-phys-as-extra-pois", "map-mon-phys-as-extra-pois");
        p.put("map-mon-regen", "map-mon-regen");
        p.put("map-mon-velocity%", "map-mon-velocity%");
        p.put("map-play-ac%", "map-play-ac%");
        p.put("map-play-addxp", "map-play-addxp");
        p.put("map-play-balance1", "map-play-balance1");
        p.put("map-play-block", "map-play-block");
        p.put("map-play-mag-gold%", "map-play-mag-gold%");
        p.put("map-play-regen", "map-play-regen");
        p.put("map-play-res-all", "map-play-res-all");
        p.put("map-play-speed-all", "map-play-speed-all");
        p.put("max-deadly", "max-deadly");
        p.put("maxcurse", "maxcurse");
        p.put("maxlevel-clout", "maxlevel-clout");
        p.put("mindmg/energy", "mindmg/energy");
        p.put("move2", "move2");
        p.put("nec", "nec");
        p.put("no-wolves", "no-wolves");
        p.put("nofreeze", "nofreeze");
        p.put("noheal", "noheal");
        p.put("openwounds", "openwounds");
        p.put("oskill", "oskill");
        p.put("pal", "pal");
        p.put("pierce", "pierce");
        p.put("pierce-cold", "pierce-cold");
        p.put("pierce-fire", "pierce-fire");
        p.put("pierce-ltng", "pierce-ltng");
        p.put("pierce-phys", "pierce-phys");
        p.put("pierce-pois", "pierce-pois");
        p.put("pois-len", "pois-len");
        p.put("pois-max", "pois-max");
        p.put("pois-min", "pois-min");
        p.put("poisskill", "poisskill");
        p.put("randclassskill1", "randclassskill1");
        p.put("randclassskill2", "randclassskill2");
        p.put("rathma-clout", "rathma-clout");
        p.put("reanimate", "reanimate");
        p.put("red-dmg", "red-dmg");
        p.put("red-dmg%", "red-dmg%");
        p.put("red-mag", "red-mag");
        p.put("reduce-ac", "reduce-ac");
        p.put("regen", "regen");
        p.put("regen-mana", "regen-mana");
        p.put("regen-stam", "regen-stam");
        p.put("rep-charge", "rep-charge");
        p.put("rep-dur", "rep-dur");
        p.put("res-all", "res-all");
        p.put("res-all-max", "res-all-max");
        p.put("res-cold", "res-cold");
        p.put("res-cold-max", "res-cold-max");
        p.put("res-fire", "res-fire");
        p.put("res-fire-max", "res-fire-max");
        p.put("res-ltng", "res-ltng");
        p.put("res-ltng-max", "res-ltng-max");
        p.put("res-pois", "res-pois");
        p.put("res-pois-len", "res-pois-len");
        p.put("res-pois-max", "res-pois-max");
        p.put("rip", "rip");
        p.put("skill", "skill");
        p.put("skill-rand", "skill-rand");
        p.put("skilltab", "skilltab");
        p.put("slow", "slow");
        p.put("sock", "sock");
        p.put("socketed-text", "socketed-text");
        p.put("sor", "sor");
        p.put("sorc-skill-rand-ctc", "sorc-skill-rand-ctc");
        p.put("splash%/missinghp%", "splash%/missinghp%");
        p.put("stam", "stam");
        p.put("stamdrain", "stamdrain");
        p.put("state", "state");
        p.put("str", "str");
        p.put("str/lvl", "str/lvl");
        p.put("stupidity", "stupidity");
        p.put("swing1", "swing1");
        p.put("swing2", "swing2");
        p.put("swing3", "swing3");
        p.put("thorns", "thorns");
        p.put("thorns/lvl", "thorns/lvl");
        p.put("vit", "vit");
        p.put("vit/lvl", "vit/lvl");
        PROP_MAP = Collections.unmodifiableMap(p);


        ArrayList<String> types = new ArrayList<>();
        types.add("Helm");
        types.add("Armor");
        types.add("Gloves");
        types.add("Boots");
        types.add("Belt");
        types.add("Amulet");
        types.add("Ring1");
        types.add("Weapon");
        types.add("Offhand");
        TYPES = types;
        //
    /*
    Helm
    Armor
    Gloves
    Boots
    Belt
    Amulet
    Ring1
    Weapon
    Offhand
     */
        LinkedHashMap<String, String> t = new LinkedHashMap<>();
        t.put("2-Handed Sword", "Weapon");
        t.put("Aerin Shield", "Offhand");
        t.put("Alpha Helm", "Helm");
        t.put("Amulet", "Amulet");
        t.put("Ancient Axe", "Weapon");
        t.put("Ancient Shield", "Offhand");
        t.put("Ancient Sword", "Weapon");
        t.put("AncientArmor", "Armor");
        t.put("Arbalest", "Weapon");
        t.put("Archon Plate", "Armor");
        t.put("Axe", "Weapon");
        t.put("Balista", "Weapon");
        t.put("Balrog Skin", "Armor");
        t.put("Barbed Club", "Weapon");
        t.put("Barbed Shield", "Offhand");
        t.put("Bardiche", "Weapon");
        t.put("Basinet", "Helm");
        t.put("Bastard Sword", "Weapon");
        t.put("Battle Axe", "Weapon");
        t.put("Battle Belt", "Belt");
        t.put("Battle Boots", "Boots");
        t.put("Battle Guantlets", "Gloves");
        t.put("Battle Hammer", "Weapon");
        t.put("Battle Scythe", "Weapon");
        t.put("Battle Staff", "Weapon");
        t.put("Battle Sword", "Weapon");
        t.put("Bearded Axe", "Weapon");
        t.put("Bec-de-Corbin", "Weapon");
        t.put("Belt", "Belt");
        t.put("Bill", "Weapon");
        t.put("Blade", "Weapon");
        t.put("Bone Helm", "Helm");
        t.put("Bone Knife", "Weapon");
        t.put("Bone Shield", "Offhand");
        t.put("Bone Wand", "Weapon");
        t.put("Boneweave", "Armor");
        t.put("Bracers", "Gloves");
        t.put("Bramble Mitts", "Gloves");
        t.put("Brandistock", "Weapon");
        t.put("Breast Plate", "Armor");
        t.put("Broad Axe", "Weapon");
        t.put("Broad Sword", "Weapon");
        t.put("Buckler", "Offhand");
        t.put("Burnt Wand", "Weapon");
        t.put("Cap", "Helm");
        t.put("Casque", "Helm");
        t.put("Cedar Staff", "Weapon");
        t.put("CedarBow", "Weapon");
        t.put("Ceremonial Bow", "Weapon");
        t.put("Ceremonial Javelin", "Weapon");
        t.put("Ceremonial Pike", "Weapon");
        t.put("Chain Boots", "Boots");
        t.put("Chain Mail", "Armor");
        t.put("Champion Axe", "Weapon");
        t.put("Champion Sword", "Weapon");
        t.put("Chaos Armor", "Armor");
        t.put("Chu-Ko-Nu", "Weapon");
        t.put("Cinquedeas", "Weapon");
        t.put("Claymore", "Weapon");
        t.put("Cleaver", "Weapon");
        t.put("Club", "Weapon");
        t.put("Colossal Sword", "Weapon");
        t.put("Colossus Blade", "Weapon");
        t.put("Colossus Girdle", "Weapon");
        t.put("Composite Bow", "Weapon");
        t.put("Conquest Sword", "Weapon");
        t.put("Crossbow", "Weapon");
        t.put("Crowbill", "Weapon");
        t.put("Crown", "Helm");
        t.put("Crusader Bow", "Weapon");
        t.put("Crusader Guantlets", "Gloves");
        t.put("Crystal Sword", "Weapon");
        t.put("Crystalline Globe", "Weapon");
        t.put("Cudgel", "Weapon");
        t.put("Cuirass", "Armor");
        t.put("Cutlass", "Weapon");
        t.put("Dacian Falx", "Weapon");
        t.put("Dagger", "Weapon");
        t.put("Death Mask", "Helm");
        t.put("Decapitator", "Weapon");
        t.put("Defender", "Offhand");
        t.put("Demonhide Armor", "Armor");
        t.put("Demonhide Boots", "Boots");
        t.put("Demonhide Gloves", "Gloves");
        t.put("Demonhide Sash", "Belt");
        t.put("Devil Star", "Weapon");
        t.put("Diamond Mail", "Armor");
        t.put("Dimensional Blade", "Weapon");
        t.put("Dirk", "Weapon");
        t.put("Divine Scepter", "Weapon");
        t.put("Double Axe", "Weapon");
        t.put("Double Bow", "Weapon");
        t.put("Dragon Shield", "Offhand");
        t.put("Dream Spirit", "Helm");
        t.put("Edge Bow", "Weapon");
        t.put("Embossed Plate", "Armor");
        t.put("Espadon", "Weapon");
        t.put("Executioner Sword", "Weapon");
        t.put("Falchion", "Weapon");
        t.put("Field Plate", "Armor");
        t.put("Flail", "Weapon");
        t.put("Flamberge", "Weapon");
        t.put("Flanged Mace", "Weapon");
        t.put("Francisca", "Weapon");
        t.put("Full Helm", "Helm");
        t.put("Full Plate Mail", "Armor");
        t.put("Fuscina", "Weapon");
        t.put("Gauntlets", "Gloves");
        t.put("Ghost Armor", "Armor");
        t.put("Ghost Spear", "Weapon");
        t.put("Giant Axe", "Weapon");
        t.put("Giant Conch", "Helm");
        t.put("Giant Sword", "Weapon");
        t.put("Giant Thresher", "Weapon");
        t.put("Girdle", "Belt");
        t.put("Gladius", "Weapon");
        t.put("Gloves", "Gloves");
        t.put("Glowing Orb", "Weapon");
        t.put("Gnarled Staff", "Weapon");
        t.put("Gothic Axe", "Weapon");
        t.put("Gothic Bow", "Weapon");
        t.put("Gothic Plate", "Armor");
        t.put("Gothic Shield", "Offhand");
        t.put("Gothic Staff", "Weapon");
        t.put("Gothic Sword", "Weapon");
        t.put("Grand Crown", "Helm");
        t.put("Grand Matron Bow", "Weapon");
        t.put("Grand Scepter", "Weapon");
        t.put("Grave Wand", "Weapon");
        t.put("Great Axe", "Weapon");
        t.put("Great Helm", "Helm");
        t.put("Great Maul", "Weapon");
        t.put("Great Sword", "Weapon");
        t.put("Grim Helm", "Helm");
        t.put("Grim Scythe", "Weapon");
        t.put("Grim Shield", "Offhand");
        t.put("Grim Wand", "Weapon");
        t.put("Guardian Crown", "Helm");
        t.put("Halberd", "Weapon");
        t.put("Hammer", "Weapon");
        t.put("Hand Axe", "Weapon");
        t.put("Hard Leather", "Armor");
        t.put("Hatchet", "Weapon");
        t.put("Hawk Helm", "Helm");
        t.put("Heavy Belt", "Belt");
        t.put("Heavy Boots", "Boots");
        t.put("Heavy Bracers", "Gloves");
        t.put("Heavy Crossbow", "Weapon");
        t.put("Heavy Gloves", "Gloves");
        t.put("Heirophant Trophy", "Offhand");
        t.put("Hellspawn Skull", "Offhand");
        t.put("Helm", "Helm");
        t.put("Heraldic Shield", "Offhand");
        t.put("Highland Blade", "Weapon");
        t.put("Holy Water Sprinkler", "Weapon");
        t.put("Hunter�s Bow", "Weapon");
        t.put("Hydra Bow", "Weapon");
        t.put("Hyperion", "Offhand");
        t.put("Jagged Star", "Weapon");
        t.put("Jawbone Visor", "Helm");
        t.put("Jo Stalf", "Weapon");
        t.put("Kite Shield", "Offhand");
        t.put("Knout", "Weapon");
        t.put("Kris", "Weapon");
        t.put("Lacquered Plate", "Armor");
        t.put("Lance", "Weapon");
        t.put("Large Axe", "Weapon");
        t.put("Large Shield", "Offhand");
        t.put("Leather Armor", "Armor");
        t.put("Leather Boots", "Boots");
        t.put("Legendary Mallet", "Weapon");
        t.put("Light Belt", "Belt");
        t.put("Light Crossbow", "Weapon");
        t.put("Light Gauntlets", "Gloves");
        t.put("Light Plate", "Armor");
        t.put("Light Plate Boots", "Boots");
        t.put("Linked Mail", "Armor");
        t.put("Lion Helm", "Helm");
        t.put("Lochaber Axe", "Weapon");
        t.put("Long Battle Bow", "Weapon");
        t.put("Long Bow", "Weapon");
        t.put("Long Siege Bow", "Weapon");
        t.put("Long Staff", "Weapon");
        t.put("Long Sword", "Weapon");
        t.put("Long War Bow", "Weapon");
        t.put("Luna", "Offhand");
        t.put("Mace", "Weapon");
        t.put("Mage Plate", "Armor");
        t.put("Maiden Javelin", "Weapon");
        t.put("Martel de Fer", "Weapon");
        t.put("Mask", "Helm");
        t.put("Matriarchal Pike", "Weapon");
        t.put("Maul", "Weapon");
        t.put("Mesh Armor", "Armor");
        t.put("Mesh Belt", "Belt");
        t.put("Mesh Boots", "Boots");
        t.put("Military Axe", "Weapon");
        t.put("Military Pick", "Weapon");
        t.put("Mithral Point", "Weapon");
        t.put("Monarch", "Offhand");
        t.put("Morning Star", "Weapon");
        t.put("Mummified Trophy", "Offhand");
        t.put("Naga", "Weapon");
        t.put("Ornate Armor", "Armor");
        t.put("Overseer Skull", "Offhand");
        t.put("Partizan", "Weapon");
        t.put("Pavise", "Offhand");
        t.put("Petrified Wand", "Weapon");
        t.put("Phase Blade", "Weapon");
        t.put("Pike", "Weapon");
        t.put("Plate Boots", "Boots");
        t.put("Plate Mail", "Armor");
        t.put("Poignard", "Weapon");
        t.put("Poleaxe", "Weapon");
        t.put("Quarterstaff", "Weapon");
        t.put("Quhab", "Weapon");
        t.put("Quilted Armor", "Armor");
        t.put("Razor Bow", "Weapon");
        t.put("Repeating Crossbow", "Weapon");
        t.put("Ring", "Ring1");
        t.put("Ring Mail", "Armor");
        t.put("Rondel", "Weapon");
        t.put("Round Shield", "Offhand");
        t.put("Rune Bow", "Weapon");
        t.put("Rune Scepter", "Weapon");
        t.put("Rune Staff", "Weapon");
        t.put("Rune Sword", "Weapon");
        t.put("Runic Talons", "Weapon");
        t.put("Russet Armor", "Armor");
        t.put("Saber", "Weapon");
        t.put("Sallet", "Helm");
        t.put("Sash", "Belt");
        t.put("Scale Mail", "Armor");
        t.put("Scepter", "Weapon");
        t.put("Scimitar", "Weapon");
        t.put("Scissors Suwayyah", "Weapon");
        t.put("Scutum", "Offhand");
        t.put("Scythe", "Weapon");
        t.put("Seraph Rod", "Weapon");
        t.put("SerpentSkin Armor", "Armor");
        t.put("Shako", "Helm");
        t.put("Shamshir", "Weapon");
        t.put("Sharkskin Belt", "Belt");
        t.put("Sharkskin Boots", "Boots");
        t.put("Sharkskin Gloves", "Gloves");
        t.put("Sharktooth Armor", "Armor");
        t.put("Shillelah", "Weapon");
        t.put("Short Battle Bow", "Weapon");
        t.put("Short Bow", "Weapon");
        t.put("Short Siege Bow", "Weapon");
        t.put("Short Staff", "Weapon");
        t.put("Short Sword", "Weapon");
        t.put("Short War Bow", "Weapon");
        t.put("Siege Crossbow", "Weapon");
        t.put("Skull Cap", "Helm");
        t.put("Slayer Guard", "Helm");
        t.put("Small Shield", "Offhand");
        t.put("Spear", "Weapon");
        t.put("Spetum", "Weapon");
        t.put("Spiked Club", "Weapon");
        t.put("Spiked Shield", "Offhand");
        t.put("Spired Helm", "Helm");
        t.put("Splint Mail", "Armor");
        t.put("Staff", "Weapon");
        t.put("Stilleto", "Weapon");
        t.put("Studded Leather", "Armor");
        t.put("Sun Spirit", "Helm");
        t.put("Swirling Crystal", "Weapon");
        t.put("Tabar", "Weapon");
        t.put("Templar Coat", "Armor");
        t.put("Thunder Maul", "Weapon");
        t.put("Tigulated Mail", "Armor");
        t.put("Tomb Wand", "Weapon");
        t.put("Tower Shield", "Offhand");
        t.put("Tresllised Armor", "Armor");
        t.put("Trident", "Weapon");
        t.put("Troll Belt", "Belt");
        t.put("Tulwar", "Weapon");
        t.put("Tusk Sword", "Weapon");
        t.put("Twin Axe", "Weapon");
        t.put("Voulge", "Weapon");
        t.put("Wand", "Weapon");
        t.put("War Axe", "Weapon");
        t.put("War Belt", "Belt");
        t.put("War Boots", "Boots");
        t.put("War Club", "Weapon");
        t.put("War Fork", "Weapon");
        t.put("War Gauntlets", "Gloves");
        t.put("War Hammer", "Weapon");
        t.put("War Hat", "Helm");
        t.put("War Scepter", "Weapon");
        t.put("War Scythe", "Weapon");
        t.put("War Spear", "Weapon");
        t.put("War Staff", "Weapon");
        t.put("War Sword", "Weapon");
        t.put("Winged Helm", "Helm");
        t.put("Wire Fleece", "Armor");
        t.put("Yari", "Weapon");
        t.put("Yew Wand", "Weapon");
        t.put("Zweihander", "Weapon");
        t.put("aegis", "Offhand");
        t.put("amulet", "Amulet");
        t.put("archon staff", "Weapon");
        t.put("armet", "Helm");
        t.put("ataghan", "Weapon");
        t.put("balrog blade", "Weapon");
        t.put("balrog spear", "Weapon");
        t.put("battle cestus", "Weapon");
        t.put("battle dart", "Weapon");
        t.put("berserker axe", "Weapon");
        t.put("blade barrier", "Offhand");
        t.put("blood spirit", "Helm");
        t.put("bloodlord skull", "Offhand");
        t.put("bone visage", "Helm");
        t.put("boneweave boots", "Offhand");
        t.put("caduceus", "Weapon");
        t.put("colossus crossbow", "Weapon");
        t.put("conqueror crown", "Helm");
        t.put("corona", "Helm");
        t.put("cryptic axe", "Weapon");
        t.put("cryptic sword", "Weapon");
        t.put("demon crossbow", "Weapon");
        t.put("demonhead", "Helm");
        t.put("destroyer helm", "Helm");
        t.put("diadem", "Helm");
        t.put("dimensional shard", "Weapon");
        t.put("dusk shroud", "Armor");
        t.put("earth spirit", "Helm");
        t.put("elder staff", "Weapon");
        t.put("eldritch orb", "Weapon");
        t.put("elegant blade", "Weapon");
        t.put("ettin axe", "Weapon");
        t.put("fanged knife", "Weapon");
        t.put("feral claws", "Weapon");
        t.put("flying axe", "Weapon");
        t.put("fury visor", "Helm");
        t.put("ghost glaive", "Weapon");
        t.put("glorious axe", "Weapon");
        t.put("hurlbat", "Weapon");
        t.put("hyperion spear", "Weapon");
        t.put("kraken shell", "Armor");
        t.put("legend spike", "Weapon");
        t.put("legendary mallet", "Weapon");
        t.put("lich wand", "Weapon");
        t.put("matriarchal bow", "Weapon");
        t.put("matriarchal javelin", "Weapon");
        t.put("matriarchal spear", "Weapon");
        t.put("mighty scepter", "Weapon");
        t.put("mirrored boots", "Boots");
        t.put("mithril coil", "Belt");
        t.put("myrmidon greaves", "Boots");
        t.put("ogre axe", "Weapon");
        t.put("ogre gauntlets", "Gloves");
        t.put("ogre maul", "Weapon");
        t.put("phase blade", "Weapon");
        t.put("ring", "Ring1");
        t.put("sacred armor", "Armor");
        t.put("sacred rondache", "Offhand");
        t.put("scarabshell boots", "Boots");
        t.put("scourge", "Weapon");
        t.put("shadow plate", "Armor");
        t.put("silver-edged axe", "Weapon");
        t.put("sky spirit", "Helm");
        t.put("spiderweb sash", "Belt");
        t.put("spired helm", "Helm");
        t.put("succubae skull", "Offhand");
        t.put("thresher", "Weapon");
        t.put("thunder maul", "Weapon");
        t.put("tiara", "Helm");
        t.put("tomahawk", "Weapon");
        t.put("troll nest", "Offhand");
        t.put("truncheon", "Weapon");
        t.put("tyrant club", "Weapon");
        t.put("unearthed wand", "Weapon");
        t.put("vambraces", "Gloves");
        t.put("vampirebone gloves", "Gloves");
        t.put("vampirefang belt", "Belt");
        t.put("vortex shield", "Offhand");
        t.put("war fist", "Weapon");
        t.put("war fork", "Weapon");
        t.put("war pike", "Weapon");
        t.put("war spike", "Weapon");
        t.put("ward", "Weapon");
        t.put("ward bow", "Weapon");
        t.put("winged axe", "Weapon");
        t.put("winged harpoon", "Weapon");
        t.put("winged knife", "Weapon");
        t.put("wrist sword", "Weapon");
        t.put("wyrrnhide boots", "Boots");
        t.put("zakarum shield", "Offhand");
        TYPE_MAP = Collections.unmodifiableMap(t);
    }

    private itemmap() {
    }
}
